name: sandra_contab_erp
description: "Sistema de Contabildad"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


platforms:
  android:
  ios:
  # macos:
  # windows:
  web:
  # linux:

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: ^0.20.2
  syncfusion_flutter_pdf: ^30.2.4          # PDF
  syncfusion_flutter_xlsio: ^30.2.4       # Excel
  csv: ^6.0.0
  share_plus: ^11.0.0
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  go_router: ^16.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  get_it: ^8.2.0
  injectable: ^2.4.4
  drift: ^2.19.1
  dio: ^5.6.0
  logger: ^2.4.0
  phosphor_flutter: ^2.1.0
  dotted_border: ^3.1.0
  envied: ^1.2.0
  url_launcher: ^6.2.1 # Para simular la apertura de enlaces de Google/GitHub
  email_validator: ^3.0.0 # Para validación de formato de correo
  local_auth: ^2.3.0
  shared_preferences: ^2.5.3
  lottie: ^3.1.0
  flutter_svg: ^2.0.9
  collection: ^1.18.0   # para sort
  flutter_slidable: ^4.0.0
  image_picker: ^1.0.4
  file_picker: ^10.2.4
  http: ^1.5.0
  path_provider: ^2.1.2
  path: ^1.8.3
  geolocator: ^14.0.2
  device_info_plus: ^11.5.0
  permission_handler: ^12.0.1
  crypto: ^3.0.6
  flutter_secure_storage: ^9.2.4
  opencv_dart: ^1.4.3
  image_editor_plus: ^1.0.4
  image: ^4.5.4
  provider: ^6.1.5+1
  crop_image: ^1.0.16
  google_mlkit_document_scanner: ^0.4.0
  camera: ^0.11.2
  speech_to_text: ^7.3.0
  audioplayers: ^6.5.0
  json_annotation: ^4.9.0
  build_runner: ^2.7.0
  json_serializable: ^6.11.0
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  
  injectable_generator: ^2.6.1
  drift_dev: ^2.19.1
  envied_generator: ^1.2.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
      - assets/code-epic.png
      - assets/sandra.png
      - assets/job.png
      - assets/job.contab.png
      - assets/svg/calculator.svg
      - assets/svg/invoice.svg
      - assets/svg/payroll.svg
      - assets/svg/wallet.svg
      - assets/svg/cliente.svg
      - assets/sound/home.mp3
      - assets/sound/search.mp3
      - assets/sound/salir.mp3
      - assets/sound/recorder.mp3
      - assets/sound/eliminar.mp3
      - assets/models/all-MiniLM-L6-v2.tflite
      - assets/models/vocab.txt

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
